on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: contosocontainerregistry7999.azurecr.io
        username: ${{ secrets.acr_contosocontainerregistry7999_username }}
        password: ${{ secrets.acr_contosocontainerregistry7999_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t contosocontainerregistry7999.azurecr.io/contosovideo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push contosocontainerregistry7999.azurecr.io/contosovideo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_contosovideo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep contoso-videobb16 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace contoso-videobb16`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: contoso-videobb16
        container-registry-url: contosocontainerregistry7999.azurecr.io
        container-registry-username: ${{ secrets.acr_contosocontainerregistry7999_username }}
        container-registry-password: ${{ secrets.acr_contosocontainerregistry7999_password }}
        secret-name: contosovideodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: contoso-videobb16
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          contosocontainerregistry7999.azurecr.io/contosovideo:${{ github.sha }}
        imagepullsecrets: |
          contosovideodockerauth
